// <auto-generated />
using System;
using EnergyPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnergyPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20260926190846_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnergyPlatform.Domain.AnalysisRuns.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("current_stage");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Stages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stages");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_analysis_runs");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_analysis_runs_status_requested_at");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Anomalies.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("EvidenceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evidence_hash");

                    b.Property<string>("Explanation")
                        .HasColumnType("jsonb")
                        .HasColumnName("explanation");

                    b.Property<string>("ExplanationSource")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("explanation_source");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meter_id");

                    b.Property<double>("Priority")
                        .HasColumnType("double precision")
                        .HasColumnName("priority");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("recommended_action");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_anomalies");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_anomalies_fingerprint");

                    b.HasIndex("MeterId")
                        .HasDatabaseName("ix_anomalies_meter_id");

                    b.HasIndex("AnalysisRunId", "Priority")
                        .HasDatabaseName("ix_anomalies_analysis_run_id_priority");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Anomalies.AnomalyStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnomalyId")
                        .HasColumnType("uuid")
                        .HasColumnName("anomaly_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_anomaly_status_changes");

                    b.HasIndex("AnomalyId")
                        .HasDatabaseName("ix_anomaly_status_changes_anomaly_id");

                    b.ToTable("anomaly_status_changes", (string)null);
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Events.MeterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meter_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("MeterId", "Timestamp")
                        .HasDatabaseName("ix_events_meter_id_timestamp");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Meters.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("BaselineDailyKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("baseline_daily_kwh");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("CurrentDailyKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("current_daily_kwh");

                    b.PrimitiveCollection<double[]>("HourlyBaseline")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("hourly_baseline");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("location");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meter_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<double?>("VariationPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("variation_percent");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasAlternateKey("MeterId")
                        .HasName("ak_meters_meter_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_meters_status");

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Readings.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ConsumptionKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("consumption_kwh");

                    b.Property<double>("CurrentA")
                        .HasColumnType("double precision")
                        .HasColumnName("current_a");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meter_id");

                    b.Property<double>("PowerFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("power_factor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("VoltageV")
                        .HasColumnType("double precision")
                        .HasColumnName("voltage_v");

                    b.HasKey("Id")
                        .HasName("pk_readings");

                    b.HasIndex("MeterId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("ix_readings_meter_id_timestamp");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Anomalies.Anomaly", b =>
                {
                    b.HasOne("EnergyPlatform.Domain.AnalysisRuns.AnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomalies_analysis_runs_analysis_run_id");

                    b.HasOne("EnergyPlatform.Domain.Meters.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .HasPrincipalKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomalies_meters_meter_id");
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Anomalies.AnomalyStatusChange", b =>
                {
                    b.HasOne("EnergyPlatform.Domain.Anomalies.Anomaly", null)
                        .WithMany("StatusChanges")
                        .HasForeignKey("AnomalyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_status_changes_anomalies_anomaly_id");
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Events.MeterEvent", b =>
                {
                    b.HasOne("EnergyPlatform.Domain.Meters.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .HasPrincipalKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_meters_meter_id");
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Readings.Reading", b =>
                {
                    b.HasOne("EnergyPlatform.Domain.Meters.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .HasPrincipalKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_meters_meter_id");
                });

            modelBuilder.Entity("EnergyPlatform.Domain.Anomalies.Anomaly", b =>
                {
                    b.Navigation("StatusChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
